- name: installing tomcat
  hosts: all
  become: yes
  tasks:
    - name: "installing required software"
      package: name='{{item}}' state='present'
      with_items:
        - wget
        - tree
        - java-17-amazon-corretto-devel
    - name: "checking if folder is present of tomcat"
      file:
        path: /opt/apache
        state: directory
        mode: 755

    - name: "installing tomcat"
      get_url:
        url:  https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.120/bin/apache-tomcat-9.0.120.tar.gz
        dest: /opt/apache
    - name: "untaring the tomcat"
      unarchive:
        src: /opt/apache/apache-tomcat-9.0.120.tar.gz
        dest: /opt/apache/
        remote_src: yes
    - name: "now deleting the .gz file which we downloaded"
      file:
        path: /opt/apache/apache-tomcat-9.0.120.tar.gz
        state: absent
    - name: "copy the files from source to destination"
      copy:
        src: "{{item}}"
        dest: "{{item}}"
      loop:
        - tomcat-users.xml
        - context.xml
    - name: "now changing the content of the file tomcat-users.xml"
      copy:
        src: tomcat-users.xml
        dest: /opt/apache/apache-tomcat-9.0.120/conf/tomcat-users.xml
        remote_src: yes
    - name: "now changing the content of context.xml"
      copy:
        src: context.xml
        dest: /opt/apache/apache-tomcat-9.0.120/webapps/manager/META-INF/context.xml
        remote_src: yes
    - name: "creating systemd file"
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache tomcat
          After=network.target
          [Service]
          #nai bhi likhenge to bydefault root he execute karega.
          User=root
          Group=root
          Type=forking
          #when we install java toh normally yahan jata hai.
          Environment="JAVA_HOME=/usr/lib/jvm/jre"
          Environment="CATALINA_HOME=/opt/apache/apache-tomcat-9.0.120/"
          Environment="CATALINA_PID=/opt/apache/apache-tomcat-9.0.120/temp/tomcat.pid"
          PIDFile=/opt/apache/apache-tomcat-9.0.120/temp/tomcat.pid
          ExecStart=/opt/apache/apache-tomcat-9.0.120/bin/startup.sh
          ExecStop=/opt/apache/apache-tomcat-9.0.120/bin/shutdown.sh
          Restart=on-failure

          [Install]
          WantedBy=multi-user.target
    - name: "reloading systemd"
      systemd:
        daemon_reload: yes
    - name: "starting tomcat service"
      service:
        name: tomcat.service
        state: started
    - name: "zipping the app content"
      archive:
        path:
          - maven-web-app
          - maven-web-app.war
        dest: maven.tar
        format: tar
      delegate_to: localhost
      become: no
      #That become: no overrides the play-level become: yes just for this task, so it runs as your normal local user instead of trying (and failing) to sudo.
    - name: "now we are copying the war files"
      copy:
        src: maven.tar
        dest: /home/ec2-user/
    - name: "now unzipping in the tomcat folder"
      unarchive:
        src: /home/ec2-user/maven.tar
        dest: /opt/apache/apache-tomcat-9.0.120/webapps/
        remote_src: yes
    - name: "now removing the tar and .xml files"
      file:
        path: "/home/ec2-user/{{item}}"
        state: absent
      loop:
        - maven.tar
        - tomcat-users.xml
        - context.xml
    - name: "print completion message"
      debug:
        msg: "ALL DONE!!!!!!!!!!!!!!!!!!!!!!!!!"
